# module makefile
# Auth: Ronghua Gao

OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libcom
libcom_SRC := com_exception.cc com_base_socket.cc

CFLAGS :=
CXXFLAGS :=


include $(PLATTOP)/super.mk
