# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS := pm

pm_SRC := pm.c
pm_LDLIBS := -llog -lpub -pthread -lipc -lJSON -lrt -lm
pm_LDFLAGS :=

include $(PLATHOME)/super.mk
