# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libDS
libDS_SRC := rbtree.c	\
				stree.c \
				trietree.c

CFLAGS := -I$(shell pwd)/../inc 


include $(PLATHOME)/super.mk
