# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libpINI 
libpINI_SRC := itemlist.c \
				parserINI.c \
				sectionlist.c

CFLAGS := -I$(shell pwd)/../inc 


include $(PLATHOME)/super.mk
