# module makefile
# Auth: Ronghua Gao

include $(PLATHOME)/common.mk

OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libpub 
libpub_SRC := mem.c	\
			 Socket.c

CFLAGS := -I$(shell pwd)/../inc 


include $(PLATHOME)/super.mk
