#!/bin/bash

TargetType=
LocalDir=
LocalName=
URL=
TargetList=

if [ $# -lt 1 ]
then
	echo "Bad Arguments! Use -h to see how to use"
	exit 1
fi

while getopts ":fdi:P:O:h" opt
do
	case $opt in
		f)
			if [ -z $TargetType ]
			then
				TargetType=$opt
			else
				echo "Option TargetType [$TargetType] has been set!"
				exit 1
			fi
			;;
		d)
			if [ -z $TargetType ]
			then
				TargetType=$opt
			else
				echo "Option TargetType [$TargetType] has been set!"
				exit 1
			fi
			;;
		i)
			TargetList=$OPTARG
			;;
		P) 
			LocalDir=$OPTARG
			;;
		O) 
			LocalName=$OPTARG
			;;
		h)
			printf "%s\n" "Useage: [-f|d] [-P LocalDir] [-O LoaclName] [-i listfile|URL]"
			printf "  %3s %-20s %s\n" "-f," "--file" "The target is the file(With \"d\" can only choose one)"
			printf "  %3s %-20s %s\n" "-d," "--directory" "The target is the directory(With \"f\" can only choose one)"
			printf "  %3s %-20s %s\n" "-i," "--list file" "The list of downloaded files(target must be file and other option unuse)"
			printf "  %3s %-20s %s\n" "-P," "--Local dir" "Download to the specified directory(default current dir)"
			printf "  %3s %-20s %s\n" "-O," "--Local name" "Rename to the specified name(default no rename)"
			printf "  %3s %-20s\n" "-h," "--help"
			exit 0
			;;
		:)
			echo "No argument value for option [$OPTARG]"
			exit 1
			;;
		?)
			echo "Unknow option [$OPTARG]!"
			exit 1
	esac
done

shift $(($OPTIND-1))

for args in $*
do
	if [[ ${args:0:1} = '-' ]]
	then 
		echo "Unknow option format at [$args]!"
		exit 9
	fi
done

if [[ $TargetList != '' ]]
then
	if [ ! -f $TargetList ]
	then 
		echo "Target URLs list file [$TargetList] not exists!"
		exit 1
	fi
	wget -i $TargetList
	exit 0
fi

if [ $# -ne 1 ]
then
	echo "No URL found!(Use -h to see how to use)"
	exit 9
fi

WgetCmd="wget -c"

if [ -z $TargetType ]
then
	TargetType='f'
fi

if [[ $TargetType = 'f' ]]
then
	if [ ! -z $LocalDir ]
	then
		if [ ! -d $LocalDir ]
		then
			echo "Directory [$LocalDir] not exists!"
			exit 9
		else
			if [[ ${LocalDir:0-1} = '/' ]]
			then
				LocalDir=${LocalDir%?}
			fi
		fi
	fi

	if [ ! -z $LocalName ]
	then
		WgetCmd="$WgetCmd -O $LocalDir/$LocalName"
	else
		WgetCmd="$WgetCmd -P $LocalDir"
	fi

	WgetCmd="$WgetCmd $1"

	#echo $WgetCmd
	$($WgetCmd)
	if [ $? -ne 0 ]
	then
		exit 9
	fi

	if [ $? -ne 0 ]
	then
		exit 9
	else
		exit 0
	fi
elif [[ $TargetType = 'd' ]]
then
	WgetCmd="$WgetCmd -r -np"
	if [ ! -z $LocalDir ]
	then
		if [ ! -d $LocalDir ]
		then
			echo "Directory [$LocalDir] not exists!"
			exit 9
		else
			WgetCmd="$WgetCmd -P $LocalDir"
		fi
	fi


	if [[ ${1:0-1} != '/' ]]
	then
		URL="$1/"
	else
		URL=$1
	fi

	WgetCmd="$WgetCmd $URL"
	#echo $WgetCmd
	$($WgetCmd)
	if [ $? -ne 0 ]
	then
		exit 9
	fi

	if [[ $URL == http://* ]]
	then
		DownDir=${URL#*//}
		DownDir=${DownDir%?}
	else
		DownDir=${URL%?}
	fi
	PDir=${DownDir%%/*}

	cd $LocalDir
	if [ ! -z $LocalName ]
	then
		rm -rf $LocalName
		mv $DownDir"/" $LocalName
	else
		HDir=${DownDir##*/}
		rm -rf $HDir
		mv $DownDir"/" $HDir
	fi

	rm -rf $PDir

else
	echo "Unknow Target type [$TargetType]!"
	exit 9
fi

if [ -z $LocalDir ]
then
	LocalDir='.'
fi

















