# module makefile
# Auth: Ronghua Gao

OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libpub 
libpub_SRC := comm_exception.cc

CFLAGS :=
CXXFLAGS :=


include $(PLATTOP)/super.mk
