# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libmempool
libmempool_SRC := mem_pool.c

CFLAGS := -I$(shell pwd)/../inc 


include $(PLATHOME)/super.mk
