#!/usr/bin/python

#Change Utf-8 to GB18030

import os
import sys 

if __name__=='__main__':
	if len(sys.argv) < 2 or len(sys.argv) > 3:
		print("Usage %(name)s [infilename] [|outfilename]")%{'name':sys.argv[0]}
		sys.exit(9)

	infilename = sys.argv[1]
	if len(sys.argv) == 3:
		outfilename = sys.argv[2]
	else:
		os.rename(infilename,infilename+"_bak")
		outfilename = infilename
		infilename = infilename+"_bak"

	outfd = open(outfilename,'w')

	for line in open(infilename):
	#	print(line.decode('utf-8').encode('gb18030'))
		outfd.write(line.decode('utf-8').encode('gb18030'))

	if len(sys.argv) != 3:
		os.remove(infilename)

	outfd.close()
