# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS := test

test_SRC := test.c
test_LDLIBS := -llog -lpub -pthread -lipc -lJSON -lrt -lm
test_LDFLAGS :=

include $(PLATHOME)/super.mk
