# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS :=
$(BINS)_SRC :=
$(BINS)_LDLIBS :=

LIBS := libJSON
libJSON_SRC := cJSON.c	

CFLAGS := -I$(shell pwd)/../inc 


include $(PLATHOME)/super.mk
